---
- name: Build Backend
  hosts: backend
  gather_facts: yes
  become: yes
  tasks:
    - name: Get update
      ansible.builtin.shell:
        cmd: apt-get update

    - name: Install jdk
      apt:
        name: openjdk-11-jdk
        update_cache: yes

    - name: Clone repository
      git:
        repo: https://github.com/spring-petclinic/spring-petclinic-rest.git
        dest: /home/ubuntu/spring-petclinic-rest
    
    - name: Set backend port
      ansible.builtin.shell:
        cmd: sed -i "s/server.port=..../server.port=$BACKEND_PORT/" src/main/resources/application.properties
        chdir: /home/ubuntu/spring-petclinic-rest

    - name: Change into MySQL DB
      ansible.builtin.shell:
        cmd: sed -i 's/=hsqldb/=mysql/' src/main/resources/application.properties
        chdir: /home/ubuntu/spring-petclinic-rest

    - name: Set IP adress of DB
      ansible.builtin.shell:
        cmd: sed -i "s/^spring.datasource.url.*$/spring.datasource.url=jdbc:mysql:\/\/$DB_INTERNAL_IP:3306\/petclinic?useUnicode=true/" src/main/resources/application-mysql.properties
        chdir: /home/ubuntu/spring-petclinic-rest

    - name: Run and build backend
      ansible.builtin.shell:
       cmd: ./mvnw spring-boot:run
       chdir: /home/ubuntu/spring-petclinic-rest
