---

- name: Installing Maven
  hosts: localhost
  become: yes

  tasks:

  - name: Install Maven using Ansible
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - maven

