- name: Setup NGINX Server
  hosts: localhost
  become: yes
  
  tasks:
  
  - name: "apt-get update"
    apt: 
      update_cache: yes
      
  - name: Allow everything and enable UFW
    community.general.ufw:
      state: enabled
      policy: allow
      
  - name: Set logging
    community.general.ufw:
      rule: allow
      name: OpenSSH
  
  - community.general.ufw:
      rule: allow
      name: Nginx HTTP
      
  - name: Install NGINX packages
    apt: 
      name: nginx
      state: latest
      
  - name: Start service
    service: 
      name: nginx
      state: restarted
      enabled: yes
